# Generated by Django 5.2.5 on 2026-05-10 19:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='default_qqhexk', max_length=255, verbose_name='image'),
        ),
    ]
